import type { Metadata } from "next";
import "./ui/globals.css";
import { raleway } from "@fonts";

export const metadata: Metadata = {
  title: "Ceres",
  description: "Generated by Whale Tail",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} h-screen`}>{children}</body>
    </html>
  );
}
